services:
  faster-whisper-cuda-arm64:
    platform: linux/arm64/v8
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faster-whisper-cuda-arm64
    restart: unless-stopped
    ports:
      - "10300:10300"
    environment:
      - WHISPER_MODEL=base-int8
      - WHISPER_LANG=en
      - WHISPER_BEAM=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
