services:
  faster-whisper-cuda-arm64:
    image: ghcr.io/stefanthoss/faster-whisper-cuda-arm64:latest
    container_name: faster-whisper-cuda-arm64
    restart: unless-stopped
    ports:
      - "10300:10300"
    environment:
      - WHISPER_MODEL=base-int8
      - WHISPER_LANG=en
      - WHISPER_BEAM=1
    volumes:
      - ./data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
